import assert from "node:assert/strict";
import { describe, it } from "node:test";
// @ts-expect-error contract.mjs is dynamically generated by test script
import { MAX_PENALTY_BPS, TimeLockedVaultContract, deriveKey } from "../../.test-build/contract.mjs";

const NOW = Date.parse("2026-09-14T12:00:00.000Z");
const TOMORROW = NOW + 24 * 60 * 60 * 1000;

function contract(userSecret = "") {
  const instance = new TimeLockedVaultContract();
  instance.initialize("treasury-1", userSecret);
  return instance;
}

function createStrict(instance = contract()) {
  return instance.createVault({
    owner: "alice", asset: "TEST ASSET", amount: 100n, unlockTime: TOMORROW,
    lockType: "STRICT", penaltyBps: 0, now: NOW
  });
}

function rejects(fn: () => void, code: string) {
  assert.throws(fn, (error: any) => error.code === code);
}

describe("Wave 1 time-locked vault contract", () => {
  it("initializes once and rejects re-initialization", () => {
    const instance = new TimeLockedVaultContract();
    instance.initialize("treasury-1");
    assert.equal(instance.isInitialized(), true);
    rejects(() => instance.initialize("treasury-2"), "ALREADY_INITIALIZED");
  });

  it("rejects an empty treasury and an uninitialized contract", () => {
    rejects(() => new TimeLockedVaultContract().initialize(" "), "INVALID_TREASURY");
    rejects(() => new TimeLockedVaultContract().createVault({
      owner: "alice", asset: "TEST ASSET", amount: 1n, unlockTime: TOMORROW,
      lockType: "STRICT", penaltyBps: 0, now: NOW
    }), "NOT_INITIALIZED");
  });

  it("creates valid vaults with unique ids", () => {
    const instance = contract();
    assert.equal(createStrict(instance).id, 1);
    assert.equal(instance.createVault({
      owner: "alice", asset: "TEST ASSET", amount: 5n, unlockTime: TOMORROW + 1,
      lockType: "STRICT", penaltyBps: 0, now: NOW
    }).id, 2);
  });

  it("rejects zero amounts, past unlocks, invalid modes, and oversized penalties", () => {
    rejects(() => contract().createVault({
      owner: "alice", asset: "TEST ASSET", amount: 0n, unlockTime: TOMORROW,
      lockType: "STRICT", penaltyBps: 0, now: NOW
    }), "INVALID_AMOUNT");
    rejects(() => contract().createVault({
      owner: "alice", asset: "TEST ASSET", amount: 1n, unlockTime: NOW - 1,
      lockType: "STRICT", penaltyBps: 0, now: NOW
    }), "INVALID_UNLOCK");
    rejects(() => contract().createVault({
      owner: "alice", asset: "TEST ASSET", amount: 1n, unlockTime: TOMORROW,
      lockType: "BROKEN", penaltyBps: 0, now: NOW
    }), "INVALID_LOCK_TYPE");
    assert.equal(MAX_PENALTY_BPS, 10_000);
    rejects(() => contract().createVault({
      owner: "alice", asset: "TEST ASSET", amount: 1n, unlockTime: TOMORROW,
      lockType: "PENALTY", penaltyBps: 10_001, now: NOW
    }), "INVALID_PENALTY");
  });

  it("keeps amount out of the public vault projection", () => {
    const instance = contract();
    createStrict(instance);
    assert.deepEqual(instance.listPublicVaults("alice")[0], {
      id: 1, asset: "TEST ASSET", unlockTime: TOMORROW, lockType: "STRICT", status: "ACTIVE", vaultState: "LOCKED"
    });
  });

  it("rejects early strict withdrawal and unauthorized withdrawal", () => {
    const instance = contract();
    const vault = createStrict(instance);
    const callerProof = ""; // userSecret is empty string by default
    rejects(() => instance.withdraw(vault.id, "alice", callerProof, NOW + 1), "STILL_LOCKED");
    rejects(() => instance.withdraw(vault.id, "bob", "wrong-secret", TOMORROW), "UNAUTHORIZED");
    assert.equal(instance.getVault(vault.id).status, "ACTIVE");
  });

  it("allows strict withdrawal at unlock and blocks double withdrawal", () => {
    const instance = contract();
    const vault = createStrict(instance);
    const callerProof = "";
    const result = instance.withdraw(vault.id, "alice", callerProof, TOMORROW);
    assert.equal(result.penalty, 0n);
    assert.equal(result.ownerPayout, 100n);
    assert.equal(result.vault.status, "WITHDRAWN");
    // Double withdrawal fails because vault status is WITHDRAWN
    rejects(() => instance.withdraw(vault.id, "alice", callerProof, TOMORROW + 1), "ALREADY_WITHDRAWN");
  });

  it("rejects a missing vault", () => {
    rejects(() => contract().withdraw(999, "alice", "", TOMORROW), "VAULT_NOT_FOUND");
  });

  it("calculates early penalty and treasury accounting correctly", () => {
    const instance = contract();
    const vault = instance.createVault({
      owner: "alice", asset: "TEST ASSET", amount: 10_000n, unlockTime: TOMORROW,
      lockType: "PENALTY", penaltyBps: 500, now: NOW
    });
    const callerProof = "";
    const result = instance.withdrawWithPenalty(vault.id, "alice", callerProof, NOW + 1, 500);
    assert.equal(result.penalty, 500n);
    assert.equal(result.ownerPayout, 9_500n);
    assert.equal(instance.getTreasury().balance, 500n);
  });

  it("charges no penalty after a penalty vault unlocks", () => {
    const instance = contract();
    const vault = instance.createVault({
      owner: "alice", asset: "TEST ASSET", amount: 1_000n, unlockTime: TOMORROW,
      lockType: "PENALTY", penaltyBps: 500, now: NOW
    });
    const callerProof = "";
    const result = instance.withdrawWithPenalty(vault.id, "alice", callerProof, TOMORROW, 500);
    assert.equal(result.penalty, 0n);
    assert.equal(result.ownerPayout, 1_000n);
    assert.equal(instance.getTreasury().balance, 0n);
  });

  it("normalizes strict mode penalty to zero", () => {
    const vault = contract().createVault({
      owner: "alice", asset: "TEST ASSET", amount: 10n, unlockTime: TOMORROW,
      lockType: "STRICT", penaltyBps: 500, now: NOW
    });
    assert.equal(vault.penaltyBps, 0);
  });

  it("records confirmed history and round-trips bigint state", () => {
    const instance = contract();
    const vault = instance.createVault({
      owner: "alice", asset: "TEST ASSET", amount: 12345678901234567890n,
      unlockTime: TOMORROW, lockType: "PENALTY", penaltyBps: 125, now: NOW
    });
    const callerProof = "";
    instance.withdrawWithPenalty(vault.id, "alice", callerProof, NOW + 1, 125);
    const txKinds = instance.listTransactions("alice").map((t: { kind: string }) => t.kind);
      assert.deepEqual(txKinds, ["PENALTY_WITHDRAW", "CREATE"]);
    const restored = TimeLockedVaultContract.fromJSON(instance.toJSON());
    assert.equal(restored.getVault(vault.id).amount, 12345678901234567890n);
    assert.equal(restored.getTreasury().balance, 154320986265432098n);
  });

  it("rejects unauthorized withdrawal after initialization reset", () => {
    const instance = contract();
    const vault = createStrict(instance);
    rejects(() => instance.withdraw(vault.id, "eve", "wrong-secret", TOMORROW), "UNAUTHORIZED");
  });

  it("deriveKey produces deterministic keys", () => {
    assert.equal(deriveKey("secret"), deriveKey("secret"));
    assert.notEqual(deriveKey("secret1"), deriveKey("secret2"));
  });

  it("ownerPublicKey is derived from userSecret", () => {
    const instance = contract("my-secret");
    assert.equal(instance.getOwnerPublicKey(), deriveKey("my-secret"));
  });
});